(function (angular) {

	'use strict';

	angular.module('angular.sp.list')
		.factory('spBuiltInFieldNames', [function () {
				return {
					ows_ID: { mappedName: 'Id', objectType: "Number" },
					ows_ContentTypeId: { mappedName: 'ContentTypeId', objectType: 'ContentTypeId' },
					ows_ContentType: { mappedName: 'ContentType', objectType: 'Text' },
					ows_Created: { mappedName: 'Created', objectType: 'DateTime' },
					ows_Author: { mappedName: 'Author', objectType: 'User' },
					ows_Modified: { mappedName: 'Modified', objectType: 'DateTime' },
					ows_Editor: { mappedName: 'Editor', objectType: 'User' },
					ows__HasCopyDestinations: { mappedName: '_HasCopyDestinations', objectType: 'Boolean' },
					ows__CopySource: { mappedName: '_CopySource', objectType: 'Text' },
					ows__ModerationStatus: { mappedName: '_ModerationStatus', objectType: 'ModStat' },
					ows__ModerationComments: { mappedName: '_ModerationComments', objectType: 'Note' },
					ows_FileRef: { mappedName: 'FileRef', objectType: 'Lookup' },
					ows_FileDirRef: { mappedName: 'FileDirRef', objectType: 'Lookup' },
					ows_Last_x0020_Modified: { mappedName: 'Last_x0020_Modified', objectType: 'Lookup' },
					ows_Created_x0020_Date: { mappedName: 'Created_x0020_Date', objectType: 'Lookup' },
					ows_File_x0020_Size: { mappedName: 'File_x0020_Size', objectType: 'Lookup' },
					ows_FSObjType: { mappedName: 'FSObjType', objectType: 'Lookup' },
					ows_PermMask: { mappedName: 'PermMask', objectType: 'Computed' },
					ows_CheckedOutUserId: { mappedName: 'CheckedOutUserId', objectType: 'Lookup' },
					ows_IsCheckedoutToLocal: { mappedName: 'IsCheckedoutToLocal', objectType: 'Lookup' },
					ows_CheckoutUser: { mappedName: 'CheckoutUser', objectType: 'User' },
					ows_FileLeafRef: { mappedName: 'FileLeafRef', objectType: 'File' },
					ows_UniqueId: { mappedName: 'UniqueId', objectType: 'Lookup' },
					ows_ProgId: { mappedName: 'ProgId', objectType: 'Lookup' },
					ows_ScopeId: { mappedName: 'ScopeId', objectType: 'Lookup' },
					ows_VirusStatus: { mappedName: 'VirusStatus', objectType: 'Lookup' },
					ows_CheckedOutTitle: { mappedName: 'CheckedOutTitle', objectType: 'Lookup' },
					ows__CheckinComment: { mappedName: '_CheckinComment', objectType: 'Lookup' },
					ows_LinkCheckedOutTitle: { mappedName: 'LinkCheckedOutTitle', objectType: 'Computed' },
					ows_Modified_x0020_By: { mappedName: 'Modified_x0020_By', objectType: 'Text' },
					ows_Created_x0020_By: { mappedName: 'Created_x0020_By', objectType: 'Text' },
					ows_File_x0020_Type: { mappedName: 'File_x0020_Type', objectType: 'Text' },
					ows_HTML_x0020_File_x0020_Type: { mappedName: 'HTML_x0020_File_x0020_Type', objectType: 'Text' },
					ows__SourceUrl: { mappedName: '_SourceUrl', objectType: 'Text' },
					ows__SharedFileIndex: { mappedName: '_SharedFileIndex', objectType: 'Text' },
					ows__EditMenuTableStart: { mappedName: '_EditMenuTableStart', objectType: 'Computed' },
					ows__EditMenuTableEnd: { mappedName: '_EditMenuTableEnd', objectType: 'Computed' },
					ows_LinkFilenameNoMenu: { mappedName: 'LinkFilenameNoMenu', objectType: 'Computed' },
					ows_LinkFilename: { mappedName: 'LinkFilename', objectType: 'Computed' },
					ows_DocIcon: { mappedName: 'DocIcon', objectType: 'Computed' },
					ows_ServerUrl: { mappedName: 'ServerUrl', objectType: 'Computed' },
					ows_EncodedAbsUrl: { mappedName: 'EncodedAbsUrl', objectType: 'Computed' },
					ows_BaseName: { mappedName: 'BaseName', objectType: 'Computed' },
					ows_FileSizeDisplay: { mappedName: 'FileSizeDisplay', objectType: 'Computed' },
					ows_MetaInfo: { mappedName: 'MetaInfo', objectType: 'Lookup' },
					ows__Level: { mappedName: '_Level', objectType: 'Integer' },
					ows__IsCurrentVersion: { mappedName: '_IsCurrentVersion', objectType: 'Boolean' },
					ows_SelectTitle: { mappedName: 'SelectTitle', objectType: 'Computed' },
					ows_SelectFilename: { mappedName: 'SelectFilename', objectType: 'Computed' },
					ows_Edit: { mappedName: 'Edit', objectType: 'Computed' },
					ows_owshiddenversion: { mappedName: 'owshiddenversion', objectType: 'Integer' },
					ows__UIVersion: { mappedName: '_UIVersion', objectType: 'Integer' },
					ows__UIVersionString: { mappedName: '_UIVersionString', objectType: 'Text' },
					ows_InstanceID: { mappedName: 'InstanceID', objectType: 'Integer' },
					ows_Order: { mappedName: 'Order', objectType: 'Number' },
					ows_GUID: { mappedName: 'GUID', objectType: 'Guid' },
					ows_WorkflowVersion: { mappedName: 'WorkflowVersion', objectType: 'Integer' },
					ows_WorkflowInstanceID: { mappedName: 'WorkflowInstanceID', objectType: 'Guid' },
					ows_ParentVersionString: { mappedName: 'ParentVersionString', objectType: 'Lookup' },
					ows_ParentLeafName: { mappedName: 'ParentLeafName', objectType: 'Lookup' },
					ows_Title: { mappedName: 'Title', objectType: 'Text' },
					ows_TemplateUrl: { mappedName: 'TemplateUrl', objectType: 'Text' },
					ows_xd_ProgID: { mappedName: 'xd_ProgID', objectType: 'Text' },
					ows_xd_Signature: { mappedName: 'xd_Signature', objectType: 'Boolean' },
					ows_Combine: { mappedName: 'Combine', objectType: 'Computed' },
					ows_RepairDocument: { mappedName: 'RepairDocument', objectType: 'Computed' }
				};
			}]);

})(angular);